project_id = "movtatkeydoydorkzfbi"

[functions.process-document]
verify_jwt = false

[functions.search-documents]
verify_jwt = false

[functions.indexing-status]
verify_jwt = false

[functions.log-dropbox-files]
verify_jwt = false

[functions.query-dropbox-files]
verify_jwt = false
